lab8_1_server: lab8_1_server.o
	gcc -o lab8_1_server.out lab8_1_server.o

lab8_1_server.o: lab8_1_server.c
	gcc -c -o lab8_1_server.o lab8_1_server.c

lab8_1_client: lab8_1_client.o
	gcc -o lab8_1_client.out lab8_1_client.o

lab8_1_client.o: lab8_1_client.c
	gcc -c -o lab8_1_client.o lab8_1_client.c

