lab7_1: lab7_1.o
	gcc -o lab7_1.out lab7_1.o

lab7_1.o: lab7_1.c
	gcc -c -o lab7_1.o lab7_1.c

lab7_2: lab7_2.o lab7_2_1 lab7_2_2
	gcc -o lab7_2.out lab7_2.o

lab7_2.o: lab7_2.c
	gcc -c -o lab7_2.o lab7_2.c

lab7_2_1: lab7_2_1.o
	gcc -o lab7_2_1.out lab7_2_1.o

lab7_2_1.o: lab7_2_1.c
	gcc -c -o lab7_2_1.o lab7_2_1.c

lab7_2_2: lab7_2_2.o
	gcc -o lab7_2_2.out lab7_2_2.o

lab7_2_2.o: lab7_2_2.c
	gcc -c -o lab7_2_2.o lab7_2_2.c